/*
Integration stubs

Stubs for implementing a REVER integration

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// IntegrationMoney Model for an amount plus the currency in which it is expressed. 
type IntegrationMoney struct {
	// amount (optionally with decimals), without currency symbol and thousands separator
	Amount float32 `json:"amount"`
	// three-letter code as ISO 4217 currency code.  Examples: EUR, USD, JPY, GBP... The currency must be supported by REVER. 
	Currency string `json:"currency"`
}

// NewIntegrationMoney instantiates a new IntegrationMoney object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIntegrationMoney(amount float32, currency string) *IntegrationMoney {
	this := IntegrationMoney{}
	this.Amount = amount
	this.Currency = currency
	return &this
}

// NewIntegrationMoneyWithDefaults instantiates a new IntegrationMoney object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntegrationMoneyWithDefaults() *IntegrationMoney {
	this := IntegrationMoney{}
	return &this
}

// GetAmount returns the Amount field value
func (o *IntegrationMoney) GetAmount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *IntegrationMoney) GetAmountOk() (*float32, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *IntegrationMoney) SetAmount(v float32) {
	o.Amount = v
}

// GetCurrency returns the Currency field value
func (o *IntegrationMoney) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *IntegrationMoney) GetCurrencyOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *IntegrationMoney) SetCurrency(v string) {
	o.Currency = v
}

func (o IntegrationMoney) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["amount"] = o.Amount
	}
	if true {
		toSerialize["currency"] = o.Currency
	}
	return json.Marshal(toSerialize)
}

type NullableIntegrationMoney struct {
	value *IntegrationMoney
	isSet bool
}

func (v NullableIntegrationMoney) Get() *IntegrationMoney {
	return v.value
}

func (v *NullableIntegrationMoney) Set(val *IntegrationMoney) {
	v.value = val
	v.isSet = true
}

func (v NullableIntegrationMoney) IsSet() bool {
	return v.isSet
}

func (v *NullableIntegrationMoney) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntegrationMoney(val *IntegrationMoney) *NullableIntegrationMoney {
	return &NullableIntegrationMoney{value: val, isSet: true}
}

func (v NullableIntegrationMoney) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntegrationMoney) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


