/*
Integration stubs

Stubs for implementing a REVER integration

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// IntegrationOrderBillingAddress Address for invoicing (not shipping, though it can be the same) 
type IntegrationOrderBillingAddress struct {
	AddressLine1 *string `json:"address_line_1,omitempty"`
	AddressLine2 *string `json:"address_line_2,omitempty"`
	City *string `json:"city,omitempty"`
	Company *string `json:"company,omitempty"`
	Country *string `json:"country,omitempty"`
	CountryCode *string `json:"country_code,omitempty"`
	Email *string `json:"email,omitempty"`
	FirstName *string `json:"first_name,omitempty"`
	LastName *string `json:"last_name,omitempty"`
	Phone *string `json:"phone,omitempty"`
	Postcode *string `json:"postcode,omitempty"`
	StateProvince *string `json:"state_province,omitempty"`
}

// NewIntegrationOrderBillingAddress instantiates a new IntegrationOrderBillingAddress object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIntegrationOrderBillingAddress() *IntegrationOrderBillingAddress {
	this := IntegrationOrderBillingAddress{}
	return &this
}

// NewIntegrationOrderBillingAddressWithDefaults instantiates a new IntegrationOrderBillingAddress object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntegrationOrderBillingAddressWithDefaults() *IntegrationOrderBillingAddress {
	this := IntegrationOrderBillingAddress{}
	return &this
}

// GetAddressLine1 returns the AddressLine1 field value if set, zero value otherwise.
func (o *IntegrationOrderBillingAddress) GetAddressLine1() string {
	if o == nil || isNil(o.AddressLine1) {
		var ret string
		return ret
	}
	return *o.AddressLine1
}

// GetAddressLine1Ok returns a tuple with the AddressLine1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntegrationOrderBillingAddress) GetAddressLine1Ok() (*string, bool) {
	if o == nil || isNil(o.AddressLine1) {
    return nil, false
	}
	return o.AddressLine1, true
}

// HasAddressLine1 returns a boolean if a field has been set.
func (o *IntegrationOrderBillingAddress) HasAddressLine1() bool {
	if o != nil && !isNil(o.AddressLine1) {
		return true
	}

	return false
}

// SetAddressLine1 gets a reference to the given string and assigns it to the AddressLine1 field.
func (o *IntegrationOrderBillingAddress) SetAddressLine1(v string) {
	o.AddressLine1 = &v
}

// GetAddressLine2 returns the AddressLine2 field value if set, zero value otherwise.
func (o *IntegrationOrderBillingAddress) GetAddressLine2() string {
	if o == nil || isNil(o.AddressLine2) {
		var ret string
		return ret
	}
	return *o.AddressLine2
}

// GetAddressLine2Ok returns a tuple with the AddressLine2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntegrationOrderBillingAddress) GetAddressLine2Ok() (*string, bool) {
	if o == nil || isNil(o.AddressLine2) {
    return nil, false
	}
	return o.AddressLine2, true
}

// HasAddressLine2 returns a boolean if a field has been set.
func (o *IntegrationOrderBillingAddress) HasAddressLine2() bool {
	if o != nil && !isNil(o.AddressLine2) {
		return true
	}

	return false
}

// SetAddressLine2 gets a reference to the given string and assigns it to the AddressLine2 field.
func (o *IntegrationOrderBillingAddress) SetAddressLine2(v string) {
	o.AddressLine2 = &v
}

// GetCity returns the City field value if set, zero value otherwise.
func (o *IntegrationOrderBillingAddress) GetCity() string {
	if o == nil || isNil(o.City) {
		var ret string
		return ret
	}
	return *o.City
}

// GetCityOk returns a tuple with the City field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntegrationOrderBillingAddress) GetCityOk() (*string, bool) {
	if o == nil || isNil(o.City) {
    return nil, false
	}
	return o.City, true
}

// HasCity returns a boolean if a field has been set.
func (o *IntegrationOrderBillingAddress) HasCity() bool {
	if o != nil && !isNil(o.City) {
		return true
	}

	return false
}

// SetCity gets a reference to the given string and assigns it to the City field.
func (o *IntegrationOrderBillingAddress) SetCity(v string) {
	o.City = &v
}

// GetCompany returns the Company field value if set, zero value otherwise.
func (o *IntegrationOrderBillingAddress) GetCompany() string {
	if o == nil || isNil(o.Company) {
		var ret string
		return ret
	}
	return *o.Company
}

// GetCompanyOk returns a tuple with the Company field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntegrationOrderBillingAddress) GetCompanyOk() (*string, bool) {
	if o == nil || isNil(o.Company) {
    return nil, false
	}
	return o.Company, true
}

// HasCompany returns a boolean if a field has been set.
func (o *IntegrationOrderBillingAddress) HasCompany() bool {
	if o != nil && !isNil(o.Company) {
		return true
	}

	return false
}

// SetCompany gets a reference to the given string and assigns it to the Company field.
func (o *IntegrationOrderBillingAddress) SetCompany(v string) {
	o.Company = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *IntegrationOrderBillingAddress) GetCountry() string {
	if o == nil || isNil(o.Country) {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntegrationOrderBillingAddress) GetCountryOk() (*string, bool) {
	if o == nil || isNil(o.Country) {
    return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *IntegrationOrderBillingAddress) HasCountry() bool {
	if o != nil && !isNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *IntegrationOrderBillingAddress) SetCountry(v string) {
	o.Country = &v
}

// GetCountryCode returns the CountryCode field value if set, zero value otherwise.
func (o *IntegrationOrderBillingAddress) GetCountryCode() string {
	if o == nil || isNil(o.CountryCode) {
		var ret string
		return ret
	}
	return *o.CountryCode
}

// GetCountryCodeOk returns a tuple with the CountryCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntegrationOrderBillingAddress) GetCountryCodeOk() (*string, bool) {
	if o == nil || isNil(o.CountryCode) {
    return nil, false
	}
	return o.CountryCode, true
}

// HasCountryCode returns a boolean if a field has been set.
func (o *IntegrationOrderBillingAddress) HasCountryCode() bool {
	if o != nil && !isNil(o.CountryCode) {
		return true
	}

	return false
}

// SetCountryCode gets a reference to the given string and assigns it to the CountryCode field.
func (o *IntegrationOrderBillingAddress) SetCountryCode(v string) {
	o.CountryCode = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *IntegrationOrderBillingAddress) GetEmail() string {
	if o == nil || isNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntegrationOrderBillingAddress) GetEmailOk() (*string, bool) {
	if o == nil || isNil(o.Email) {
    return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *IntegrationOrderBillingAddress) HasEmail() bool {
	if o != nil && !isNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *IntegrationOrderBillingAddress) SetEmail(v string) {
	o.Email = &v
}

// GetFirstName returns the FirstName field value if set, zero value otherwise.
func (o *IntegrationOrderBillingAddress) GetFirstName() string {
	if o == nil || isNil(o.FirstName) {
		var ret string
		return ret
	}
	return *o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntegrationOrderBillingAddress) GetFirstNameOk() (*string, bool) {
	if o == nil || isNil(o.FirstName) {
    return nil, false
	}
	return o.FirstName, true
}

// HasFirstName returns a boolean if a field has been set.
func (o *IntegrationOrderBillingAddress) HasFirstName() bool {
	if o != nil && !isNil(o.FirstName) {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given string and assigns it to the FirstName field.
func (o *IntegrationOrderBillingAddress) SetFirstName(v string) {
	o.FirstName = &v
}

// GetLastName returns the LastName field value if set, zero value otherwise.
func (o *IntegrationOrderBillingAddress) GetLastName() string {
	if o == nil || isNil(o.LastName) {
		var ret string
		return ret
	}
	return *o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntegrationOrderBillingAddress) GetLastNameOk() (*string, bool) {
	if o == nil || isNil(o.LastName) {
    return nil, false
	}
	return o.LastName, true
}

// HasLastName returns a boolean if a field has been set.
func (o *IntegrationOrderBillingAddress) HasLastName() bool {
	if o != nil && !isNil(o.LastName) {
		return true
	}

	return false
}

// SetLastName gets a reference to the given string and assigns it to the LastName field.
func (o *IntegrationOrderBillingAddress) SetLastName(v string) {
	o.LastName = &v
}

// GetPhone returns the Phone field value if set, zero value otherwise.
func (o *IntegrationOrderBillingAddress) GetPhone() string {
	if o == nil || isNil(o.Phone) {
		var ret string
		return ret
	}
	return *o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntegrationOrderBillingAddress) GetPhoneOk() (*string, bool) {
	if o == nil || isNil(o.Phone) {
    return nil, false
	}
	return o.Phone, true
}

// HasPhone returns a boolean if a field has been set.
func (o *IntegrationOrderBillingAddress) HasPhone() bool {
	if o != nil && !isNil(o.Phone) {
		return true
	}

	return false
}

// SetPhone gets a reference to the given string and assigns it to the Phone field.
func (o *IntegrationOrderBillingAddress) SetPhone(v string) {
	o.Phone = &v
}

// GetPostcode returns the Postcode field value if set, zero value otherwise.
func (o *IntegrationOrderBillingAddress) GetPostcode() string {
	if o == nil || isNil(o.Postcode) {
		var ret string
		return ret
	}
	return *o.Postcode
}

// GetPostcodeOk returns a tuple with the Postcode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntegrationOrderBillingAddress) GetPostcodeOk() (*string, bool) {
	if o == nil || isNil(o.Postcode) {
    return nil, false
	}
	return o.Postcode, true
}

// HasPostcode returns a boolean if a field has been set.
func (o *IntegrationOrderBillingAddress) HasPostcode() bool {
	if o != nil && !isNil(o.Postcode) {
		return true
	}

	return false
}

// SetPostcode gets a reference to the given string and assigns it to the Postcode field.
func (o *IntegrationOrderBillingAddress) SetPostcode(v string) {
	o.Postcode = &v
}

// GetStateProvince returns the StateProvince field value if set, zero value otherwise.
func (o *IntegrationOrderBillingAddress) GetStateProvince() string {
	if o == nil || isNil(o.StateProvince) {
		var ret string
		return ret
	}
	return *o.StateProvince
}

// GetStateProvinceOk returns a tuple with the StateProvince field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntegrationOrderBillingAddress) GetStateProvinceOk() (*string, bool) {
	if o == nil || isNil(o.StateProvince) {
    return nil, false
	}
	return o.StateProvince, true
}

// HasStateProvince returns a boolean if a field has been set.
func (o *IntegrationOrderBillingAddress) HasStateProvince() bool {
	if o != nil && !isNil(o.StateProvince) {
		return true
	}

	return false
}

// SetStateProvince gets a reference to the given string and assigns it to the StateProvince field.
func (o *IntegrationOrderBillingAddress) SetStateProvince(v string) {
	o.StateProvince = &v
}

func (o IntegrationOrderBillingAddress) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.AddressLine1) {
		toSerialize["address_line_1"] = o.AddressLine1
	}
	if !isNil(o.AddressLine2) {
		toSerialize["address_line_2"] = o.AddressLine2
	}
	if !isNil(o.City) {
		toSerialize["city"] = o.City
	}
	if !isNil(o.Company) {
		toSerialize["company"] = o.Company
	}
	if !isNil(o.Country) {
		toSerialize["country"] = o.Country
	}
	if !isNil(o.CountryCode) {
		toSerialize["country_code"] = o.CountryCode
	}
	if !isNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !isNil(o.FirstName) {
		toSerialize["first_name"] = o.FirstName
	}
	if !isNil(o.LastName) {
		toSerialize["last_name"] = o.LastName
	}
	if !isNil(o.Phone) {
		toSerialize["phone"] = o.Phone
	}
	if !isNil(o.Postcode) {
		toSerialize["postcode"] = o.Postcode
	}
	if !isNil(o.StateProvince) {
		toSerialize["state_province"] = o.StateProvince
	}
	return json.Marshal(toSerialize)
}

type NullableIntegrationOrderBillingAddress struct {
	value *IntegrationOrderBillingAddress
	isSet bool
}

func (v NullableIntegrationOrderBillingAddress) Get() *IntegrationOrderBillingAddress {
	return v.value
}

func (v *NullableIntegrationOrderBillingAddress) Set(val *IntegrationOrderBillingAddress) {
	v.value = val
	v.isSet = true
}

func (v NullableIntegrationOrderBillingAddress) IsSet() bool {
	return v.isSet
}

func (v *NullableIntegrationOrderBillingAddress) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntegrationOrderBillingAddress(val *IntegrationOrderBillingAddress) *NullableIntegrationOrderBillingAddress {
	return &NullableIntegrationOrderBillingAddress{value: val, isSet: true}
}

func (v NullableIntegrationOrderBillingAddress) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntegrationOrderBillingAddress) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


