/*
Integration stubs

Stubs for implementing a REVER integration

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// IntegrationShippingAmountCustomer Total amount charged as shipping costs in the customer currency. This is the amount displayed to the customer. 
type IntegrationShippingAmountCustomer struct {
	// amount (optionally with decimals), without currency symbol and thousands separator
	Amount float32 `json:"amount"`
	// three-letter code as ISO 4217 currency code.  Examples: EUR, USD, JPY, GBP... The currency must be supported by REVER. 
	Currency string `json:"currency"`
}

// NewIntegrationShippingAmountCustomer instantiates a new IntegrationShippingAmountCustomer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIntegrationShippingAmountCustomer(amount float32, currency string) *IntegrationShippingAmountCustomer {
	this := IntegrationShippingAmountCustomer{}
	this.Amount = amount
	this.Currency = currency
	return &this
}

// NewIntegrationShippingAmountCustomerWithDefaults instantiates a new IntegrationShippingAmountCustomer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntegrationShippingAmountCustomerWithDefaults() *IntegrationShippingAmountCustomer {
	this := IntegrationShippingAmountCustomer{}
	return &this
}

// GetAmount returns the Amount field value
func (o *IntegrationShippingAmountCustomer) GetAmount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *IntegrationShippingAmountCustomer) GetAmountOk() (*float32, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *IntegrationShippingAmountCustomer) SetAmount(v float32) {
	o.Amount = v
}

// GetCurrency returns the Currency field value
func (o *IntegrationShippingAmountCustomer) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *IntegrationShippingAmountCustomer) GetCurrencyOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *IntegrationShippingAmountCustomer) SetCurrency(v string) {
	o.Currency = v
}

func (o IntegrationShippingAmountCustomer) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["amount"] = o.Amount
	}
	if true {
		toSerialize["currency"] = o.Currency
	}
	return json.Marshal(toSerialize)
}

type NullableIntegrationShippingAmountCustomer struct {
	value *IntegrationShippingAmountCustomer
	isSet bool
}

func (v NullableIntegrationShippingAmountCustomer) Get() *IntegrationShippingAmountCustomer {
	return v.value
}

func (v *NullableIntegrationShippingAmountCustomer) Set(val *IntegrationShippingAmountCustomer) {
	v.value = val
	v.isSet = true
}

func (v NullableIntegrationShippingAmountCustomer) IsSet() bool {
	return v.isSet
}

func (v *NullableIntegrationShippingAmountCustomer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntegrationShippingAmountCustomer(val *IntegrationShippingAmountCustomer) *NullableIntegrationShippingAmountCustomer {
	return &NullableIntegrationShippingAmountCustomer{value: val, isSet: true}
}

func (v NullableIntegrationShippingAmountCustomer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntegrationShippingAmountCustomer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


