
OPENAPI_URL=https://api.byrever.com/v1/docs/openapi_integration.yaml
OPENAPI_LOCAL=tmp/openapi.yaml
CLIENT_PATH=client
SERVER_PATH=server

##############################
# SERVER MOCK IMPLEMENTATION #
##############################

run-server:
	go run server/main.go

##################
# API GENERATION #
##################

clear-client:
	rm -rf ${CLIENT_PATH}

# server folder contains non-autogenerated code, can't be removed
clear-server:

clean-client:
	echo Cleaning up...
	rm -rf ${CLIENT_PATH}/.openapi-generator
	rm -rf ${CLIENT_PATH}/api
	rm -rf ${CLIENT_PATH}/docs
	rm -rf ${CLIENT_PATH}/test
	rm -rf ${CLIENT_PATH}/.gitignore
	rm -rf ${CLIENT_PATH}/.openapi-generator-ignore
	rm -rf ${CLIENT_PATH}/.travis.yml
	rm -rf ${CLIENT_PATH}/go.mod
	rm -rf ${CLIENT_PATH}/go.sum
	rm -rf ${CLIENT_PATH}/git_push.sh
	rm -rf ${CLIENT_PATH}/README.md

clean-server:
	echo Cleaning up...
	rm -rf ${SERVER_PATH}/.openapi-generator
	rm -rf ${SERVER_PATH}/.openapi-generator-ignore
	rm -rf ${SERVER_PATH}/api
	rm -rf ${SERVER_PATH}/go.mod
	rm -rf ${SERVER_PATH}/go.sum
	rm -rf ${SERVER_PATH}/README.md
	rm -rf ${SERVER_PATH}/Dockerfile

download-openapi:
	mkdir -p tmp
	curl -o ${OPENAPI_LOCAL} ${OPENAPI_URL}

update-libs:
	go get golang.org/x/oauth2
	go get github.com/gorilla/mux
	go mod tidy
	go mod vendor

openapi-generator-cli:
	docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli:v6.2.1 generate \
	 -i /local/${OPENAPI_LOCAL} \
	--additional-properties=packageName=client \
    -g go \
    -o /local/${CLIENT_PATH}

openapi-generator-srv:
	docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli:v6.2.1 generate \
	 -i /local/${OPENAPI_LOCAL} \
	--additional-properties=packageName=server \
    -g go-server \
	--git-repo-id=integration/server --git-user-id=itsrever \
	--ignore-file-override=/local/.openapi-generator-ignore \
    -o /local/${SERVER_PATH}

gen-go-client: download-openapi clear-client openapi-generator-cli clean-client update-libs
gen-go-server: download-openapi clear-server openapi-generator-srv clean-server update-libs
	