/*
 * Integration stubs
 *
 * Stubs for implementing a REVER integration
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

import (
	"context"
	"log"
)

// IntegrationApiService is a service that implements the logic for the IntegrationApiServicer
// This service should implement the business logic for every endpoint for the IntegrationApi API.
// Include any external packages or services that will be required by this service.
type IntegrationApiService struct {
}

// NewIntegrationApiService creates a default api service
func NewIntegrationApiService() IntegrationApiServicer {
	return &IntegrationApiService{}
}

// FindOrderByCustomerOrderPrintedId - Find Order by customer_order_id
func (s *IntegrationApiService) FindOrderByCustomerOrderPrintedId(ctx context.Context, customerOrderPrintedId string) (ImplResponse, error) {
	log.Printf("CONTEXT %+\n", ctx)
	return Response(200, IntegrationOrder{}), nil
}
