/*
 * Integration stubs
 *
 * Stubs for implementing a REVER integration
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

// OrderTotalTaxes - Total taxes of the order 
type OrderTotalTaxes struct {

	AmountShop MultiMoneyAmountShop `json:"amount_shop"`

	AmountCustomer MultiMoneyAmountCustomer `json:"amount_customer"`
}

// AssertOrderTotalTaxesRequired checks if the required fields are not zero-ed
func AssertOrderTotalTaxesRequired(obj OrderTotalTaxes) error {
	elements := map[string]interface{}{
		"amount_shop": obj.AmountShop,
		"amount_customer": obj.AmountCustomer,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertMultiMoneyAmountShopRequired(obj.AmountShop); err != nil {
		return err
	}
	if err := AssertMultiMoneyAmountCustomerRequired(obj.AmountCustomer); err != nil {
		return err
	}
	return nil
}

// AssertRecurseOrderTotalTaxesRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of OrderTotalTaxes (e.g. [][]OrderTotalTaxes), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseOrderTotalTaxesRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aOrderTotalTaxes, ok := obj.(OrderTotalTaxes)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertOrderTotalTaxesRequired(aOrderTotalTaxes)
	})
}
