/*
 * Integration stubs
 *
 * Stubs for implementing a REVER integration
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

// IntegrationProductPrice - price per unit of the product in the shop currency. Should be present if there are no variants.
type IntegrationProductPrice struct {

	// amount (optionally with decimals), without currency symbol and thousands separator
	Amount float32 `json:"amount"`

	// three-letter code as ISO 4217 currency code.  Examples: EUR, USD, JPY, GBP... The currency must be supported by REVER. 
	Currency string `json:"currency"`
}

// AssertIntegrationProductPriceRequired checks if the required fields are not zero-ed
func AssertIntegrationProductPriceRequired(obj IntegrationProductPrice) error {
	elements := map[string]interface{}{
		"amount": obj.Amount,
		"currency": obj.Currency,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseIntegrationProductPriceRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of IntegrationProductPrice (e.g. [][]IntegrationProductPrice), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseIntegrationProductPriceRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aIntegrationProductPrice, ok := obj.(IntegrationProductPrice)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertIntegrationProductPriceRequired(aIntegrationProductPrice)
	})
}
