/*
 * Integration stubs
 *
 * Stubs for implementing a REVER integration
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

// IntegrationFulfillment - Line item fulfilled in an order
type IntegrationFulfillment struct {

	// ID of the line item being fulfilled. Must exist in the `line_items` array of the order.
	LineItemId string `json:"line_item_id"`

	// Number of products fulfilled. The sum of quantities per `line_item_id` must match the total quantity of the line item.
	Quantity float32 `json:"quantity"`
}

// AssertIntegrationFulfillmentRequired checks if the required fields are not zero-ed
func AssertIntegrationFulfillmentRequired(obj IntegrationFulfillment) error {
	elements := map[string]interface{}{
		"line_item_id": obj.LineItemId,
		"quantity": obj.Quantity,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseIntegrationFulfillmentRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of IntegrationFulfillment (e.g. [][]IntegrationFulfillment), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseIntegrationFulfillmentRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aIntegrationFulfillment, ok := obj.(IntegrationFulfillment)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertIntegrationFulfillmentRequired(aIntegrationFulfillment)
	})
}
