/*
 * Integration stubs
 *
 * Stubs for implementing a REVER integration
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

// LineItemTotalDiscounts - total amount of discounts applied to this line item. Each item of this line item has a proportional discount.
type LineItemTotalDiscounts struct {

	AmountShop MultiMoneyAmountShop `json:"amount_shop"`

	AmountCustomer MultiMoneyAmountCustomer `json:"amount_customer"`
}

// AssertLineItemTotalDiscountsRequired checks if the required fields are not zero-ed
func AssertLineItemTotalDiscountsRequired(obj LineItemTotalDiscounts) error {
	elements := map[string]interface{}{
		"amount_shop": obj.AmountShop,
		"amount_customer": obj.AmountCustomer,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertMultiMoneyAmountShopRequired(obj.AmountShop); err != nil {
		return err
	}
	if err := AssertMultiMoneyAmountCustomerRequired(obj.AmountCustomer); err != nil {
		return err
	}
	return nil
}

// AssertRecurseLineItemTotalDiscountsRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of LineItemTotalDiscounts (e.g. [][]LineItemTotalDiscounts), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseLineItemTotalDiscountsRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aLineItemTotalDiscounts, ok := obj.(LineItemTotalDiscounts)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertLineItemTotalDiscountsRequired(aLineItemTotalDiscounts)
	})
}
