/*
 * Integration stubs
 *
 * Stubs for implementing a REVER integration
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

// IntegrationLineItemSubtotal - sub total amount of the line before discounts and taxes `subtotal = unit_price * quantity`
type IntegrationLineItemSubtotal struct {

	AmountShop IntegrationMultiMoneyAmountShop `json:"amount_shop"`

	AmountCustomer IntegrationMultiMoneyAmountCustomer `json:"amount_customer"`
}

// AssertIntegrationLineItemSubtotalRequired checks if the required fields are not zero-ed
func AssertIntegrationLineItemSubtotalRequired(obj IntegrationLineItemSubtotal) error {
	elements := map[string]interface{}{
		"amount_shop": obj.AmountShop,
		"amount_customer": obj.AmountCustomer,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertIntegrationMultiMoneyAmountShopRequired(obj.AmountShop); err != nil {
		return err
	}
	if err := AssertIntegrationMultiMoneyAmountCustomerRequired(obj.AmountCustomer); err != nil {
		return err
	}
	return nil
}

// AssertRecurseIntegrationLineItemSubtotalRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of IntegrationLineItemSubtotal (e.g. [][]IntegrationLineItemSubtotal), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseIntegrationLineItemSubtotalRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aIntegrationLineItemSubtotal, ok := obj.(IntegrationLineItemSubtotal)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertIntegrationLineItemSubtotalRequired(aIntegrationLineItemSubtotal)
	})
}
