/*
 * Integration stubs
 *
 * Stubs for implementing a REVER integration
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

// MultiMoneyAmountShop - Amount in the shop currency.  Useful for accounting purposes, to provide reporting in this currency.  Usually, the shop currency is the same for every order within the e-commerce. 
type MultiMoneyAmountShop struct {

	// amount (optionally with decimals), without currency symbol and thousands separator
	Amount float64 `json:"amount"`

	// three-letter code as ISO 4217 currency code.  Examples: EUR, USD, JPY, GBP... The currency must be supported by REVER. 
	Currency string `json:"currency"`
}

// AssertMultiMoneyAmountShopRequired checks if the required fields are not zero-ed
func AssertMultiMoneyAmountShopRequired(obj MultiMoneyAmountShop) error {
	elements := map[string]interface{}{
		"amount": obj.Amount,
		"currency": obj.Currency,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseMultiMoneyAmountShopRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of MultiMoneyAmountShop (e.g. [][]MultiMoneyAmountShop), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseMultiMoneyAmountShopRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aMultiMoneyAmountShop, ok := obj.(MultiMoneyAmountShop)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertMultiMoneyAmountShopRequired(aMultiMoneyAmountShop)
	})
}
