/*
 * Integration stubs
 *
 * Stubs for implementing a REVER integration
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

// IntegrationOrderTotalAmount - Total amount of the order, including taxes, discounts and shipping costs. Must match the sum of the `line_items`  using the shop and customer currency, plus the shipping costs. 
type IntegrationOrderTotalAmount struct {

	AmountShop IntegrationMultiMoneyAmountShop `json:"amount_shop"`

	AmountCustomer IntegrationMultiMoneyAmountCustomer `json:"amount_customer"`
}

// AssertIntegrationOrderTotalAmountRequired checks if the required fields are not zero-ed
func AssertIntegrationOrderTotalAmountRequired(obj IntegrationOrderTotalAmount) error {
	elements := map[string]interface{}{
		"amount_shop": obj.AmountShop,
		"amount_customer": obj.AmountCustomer,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertIntegrationMultiMoneyAmountShopRequired(obj.AmountShop); err != nil {
		return err
	}
	if err := AssertIntegrationMultiMoneyAmountCustomerRequired(obj.AmountCustomer); err != nil {
		return err
	}
	return nil
}

// AssertRecurseIntegrationOrderTotalAmountRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of IntegrationOrderTotalAmount (e.g. [][]IntegrationOrderTotalAmount), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseIntegrationOrderTotalAmountRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aIntegrationOrderTotalAmount, ok := obj.(IntegrationOrderTotalAmount)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertIntegrationOrderTotalAmountRequired(aIntegrationOrderTotalAmount)
	})
}
