/*
 * Integration stubs
 *
 * Stubs for implementing a REVER integration
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

// IntegrationImage - An image from the e-commerce catalog
type IntegrationImage struct {

	// Image alternative text
	Alt string `json:"alt,omitempty"`

	// Image name
	Name string `json:"name,omitempty"`

	// Image URL
	Src string `json:"src"`
}

// AssertIntegrationImageRequired checks if the required fields are not zero-ed
func AssertIntegrationImageRequired(obj IntegrationImage) error {
	elements := map[string]interface{}{
		"src": obj.Src,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseIntegrationImageRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of IntegrationImage (e.g. [][]IntegrationImage), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseIntegrationImageRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aIntegrationImage, ok := obj.(IntegrationImage)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertIntegrationImageRequired(aIntegrationImage)
	})
}
