/*
 * Integration stubs
 *
 * Stubs for implementing a REVER integration
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

type CreateReturn200Response struct {

	// the id of the return generated in the platform
	ReturnId string `json:"return_id"`
}

// AssertCreateReturn200ResponseRequired checks if the required fields are not zero-ed
func AssertCreateReturn200ResponseRequired(obj CreateReturn200Response) error {
	elements := map[string]interface{}{
		"return_id": obj.ReturnId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseCreateReturn200ResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of CreateReturn200Response (e.g. [][]CreateReturn200Response), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseCreateReturn200ResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aCreateReturn200Response, ok := obj.(CreateReturn200Response)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertCreateReturn200ResponseRequired(aCreateReturn200Response)
	})
}
