/*
 * Integration stubs
 *
 * Stubs for implementing a REVER integration
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

// IntegrationVariantUnitPrice - Unit price in the shop currency. Does not include taxes nor discounts. Those will be applied later on.
type IntegrationVariantUnitPrice struct {

	// amount (optionally with decimals), without currency symbol and thousands separator
	Amount float64 `json:"amount"`

	// three-letter code as ISO 4217 currency code.  Examples: EUR, USD, JPY, GBP... The currency must be supported by REVER. 
	Currency string `json:"currency"`
}

// AssertIntegrationVariantUnitPriceRequired checks if the required fields are not zero-ed
func AssertIntegrationVariantUnitPriceRequired(obj IntegrationVariantUnitPrice) error {
	elements := map[string]interface{}{
		"amount": obj.Amount,
		"currency": obj.Currency,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseIntegrationVariantUnitPriceRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of IntegrationVariantUnitPrice (e.g. [][]IntegrationVariantUnitPrice), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseIntegrationVariantUnitPriceRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aIntegrationVariantUnitPrice, ok := obj.(IntegrationVariantUnitPrice)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertIntegrationVariantUnitPriceRequired(aIntegrationVariantUnitPrice)
	})
}
