/*
 * Integration stubs
 *
 * Stubs for implementing a REVER integration
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

// Return - A return operation executed over one or more items of an order. It might be in progress or successfully completed. 
type Return struct {

	// ID of the line item returned. Must exist in the `line_items` array of the order.
	LineItemId string `json:"line_item_id"`

	// Number of products returned. The sum of quantities per `line_item_id` must match the total quantity of the line item.
	Quantity int32 `json:"quantity"`

	Status Status `json:"status"`
}

// AssertReturnRequired checks if the required fields are not zero-ed
func AssertReturnRequired(obj Return) error {
	elements := map[string]interface{}{
		"line_item_id": obj.LineItemId,
		"quantity": obj.Quantity,
		"status": obj.Status,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertStatusRequired(obj.Status); err != nil {
		return err
	}
	return nil
}

// AssertRecurseReturnRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Return (e.g. [][]Return), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseReturnRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aReturn, ok := obj.(Return)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertReturnRequired(aReturn)
	})
}
