/*
 * Integration stubs
 *
 * Stubs for implementing a REVER integration
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

// IntegrationLineItemTotal - total amount of the line including discounts and taxes total = (subtotal - total_discounts) + total_taxes this is going to be the amount to be refunded (multiplied by items_returned/quantity)
type IntegrationLineItemTotal struct {

	AmountShop IntegrationMultiMoneyAmountShop `json:"amount_shop"`

	AmountCustomer IntegrationMultiMoneyAmountCustomer `json:"amount_customer"`
}

// AssertIntegrationLineItemTotalRequired checks if the required fields are not zero-ed
func AssertIntegrationLineItemTotalRequired(obj IntegrationLineItemTotal) error {
	elements := map[string]interface{}{
		"amount_shop": obj.AmountShop,
		"amount_customer": obj.AmountCustomer,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertIntegrationMultiMoneyAmountShopRequired(obj.AmountShop); err != nil {
		return err
	}
	if err := AssertIntegrationMultiMoneyAmountCustomerRequired(obj.AmountCustomer); err != nil {
		return err
	}
	return nil
}

// AssertRecurseIntegrationLineItemTotalRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of IntegrationLineItemTotal (e.g. [][]IntegrationLineItemTotal), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseIntegrationLineItemTotalRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aIntegrationLineItemTotal, ok := obj.(IntegrationLineItemTotal)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertIntegrationLineItemTotalRequired(aIntegrationLineItemTotal)
	})
}
