/*
 * Integration stubs
 *
 * Stubs for implementing a REVER integration
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

// IntegrationLineItemUnitPrice - unit price of a single item (product as listed, no discounts, no taxes, quantity = 1)
type IntegrationLineItemUnitPrice struct {

	AmountShop IntegrationMultiMoneyAmountShop `json:"amount_shop"`

	AmountCustomer IntegrationMultiMoneyAmountCustomer `json:"amount_customer"`
}

// AssertIntegrationLineItemUnitPriceRequired checks if the required fields are not zero-ed
func AssertIntegrationLineItemUnitPriceRequired(obj IntegrationLineItemUnitPrice) error {
	elements := map[string]interface{}{
		"amount_shop": obj.AmountShop,
		"amount_customer": obj.AmountCustomer,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertIntegrationMultiMoneyAmountShopRequired(obj.AmountShop); err != nil {
		return err
	}
	if err := AssertIntegrationMultiMoneyAmountCustomerRequired(obj.AmountCustomer); err != nil {
		return err
	}
	return nil
}

// AssertRecurseIntegrationLineItemUnitPriceRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of IntegrationLineItemUnitPrice (e.g. [][]IntegrationLineItemUnitPrice), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseIntegrationLineItemUnitPriceRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aIntegrationLineItemUnitPrice, ok := obj.(IntegrationLineItemUnitPrice)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertIntegrationLineItemUnitPriceRequired(aIntegrationLineItemUnitPrice)
	})
}
