/*
 * Integration stubs
 *
 * Stubs for implementing a REVER integration
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

// IntegrationOrderTotalTaxes - Total taxes of the order 
type IntegrationOrderTotalTaxes struct {

	AmountShop IntegrationMultiMoneyAmountShop `json:"amount_shop"`

	AmountCustomer IntegrationMultiMoneyAmountCustomer `json:"amount_customer"`
}

// AssertIntegrationOrderTotalTaxesRequired checks if the required fields are not zero-ed
func AssertIntegrationOrderTotalTaxesRequired(obj IntegrationOrderTotalTaxes) error {
	elements := map[string]interface{}{
		"amount_shop": obj.AmountShop,
		"amount_customer": obj.AmountCustomer,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertIntegrationMultiMoneyAmountShopRequired(obj.AmountShop); err != nil {
		return err
	}
	if err := AssertIntegrationMultiMoneyAmountCustomerRequired(obj.AmountCustomer); err != nil {
		return err
	}
	return nil
}

// AssertRecurseIntegrationOrderTotalTaxesRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of IntegrationOrderTotalTaxes (e.g. [][]IntegrationOrderTotalTaxes), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseIntegrationOrderTotalTaxesRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aIntegrationOrderTotalTaxes, ok := obj.(IntegrationOrderTotalTaxes)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertIntegrationOrderTotalTaxesRequired(aIntegrationOrderTotalTaxes)
	})
}
