/*
 * Integration stubs
 *
 * Stubs for implementing a REVER integration
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

// OrderTotalAmount - Total amount of the order, including taxes, discounts and shipping costs. Must match the sum of the `line_items`  using the shop and customer currency, plus the shipping costs. 
type OrderTotalAmount struct {

	AmountShop MultiMoneyAmountShop `json:"amount_shop"`

	AmountCustomer MultiMoneyAmountCustomer `json:"amount_customer"`
}

// AssertOrderTotalAmountRequired checks if the required fields are not zero-ed
func AssertOrderTotalAmountRequired(obj OrderTotalAmount) error {
	elements := map[string]interface{}{
		"amount_shop": obj.AmountShop,
		"amount_customer": obj.AmountCustomer,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertMultiMoneyAmountShopRequired(obj.AmountShop); err != nil {
		return err
	}
	if err := AssertMultiMoneyAmountCustomerRequired(obj.AmountCustomer); err != nil {
		return err
	}
	return nil
}

// AssertRecurseOrderTotalAmountRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of OrderTotalAmount (e.g. [][]OrderTotalAmount), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseOrderTotalAmountRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aOrderTotalAmount, ok := obj.(OrderTotalAmount)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertOrderTotalAmountRequired(aOrderTotalAmount)
	})
}
