/*
 * Integration stubs
 *
 * Stubs for implementing a REVER integration
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

type AddNoteToOrderRequest struct {

	// The text to be associated to the order
	Note string `json:"note,omitempty"`
}

// AssertAddNoteToOrderRequestRequired checks if the required fields are not zero-ed
func AssertAddNoteToOrderRequestRequired(obj AddNoteToOrderRequest) error {
	return nil
}

// AssertRecurseAddNoteToOrderRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of AddNoteToOrderRequest (e.g. [][]AddNoteToOrderRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseAddNoteToOrderRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aAddNoteToOrderRequest, ok := obj.(AddNoteToOrderRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertAddNoteToOrderRequestRequired(aAddNoteToOrderRequest)
	})
}
