/*
 * Integration stubs
 *
 * Stubs for implementing a REVER integration
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

// IntegrationLineItemTotalTaxes - total amount of taxes for this line. Each item of this line item has proportional taxes.
type IntegrationLineItemTotalTaxes struct {

	AmountShop IntegrationMultiMoneyAmountShop `json:"amount_shop"`

	AmountCustomer IntegrationMultiMoneyAmountCustomer `json:"amount_customer"`
}

// AssertIntegrationLineItemTotalTaxesRequired checks if the required fields are not zero-ed
func AssertIntegrationLineItemTotalTaxesRequired(obj IntegrationLineItemTotalTaxes) error {
	elements := map[string]interface{}{
		"amount_shop": obj.AmountShop,
		"amount_customer": obj.AmountCustomer,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertIntegrationMultiMoneyAmountShopRequired(obj.AmountShop); err != nil {
		return err
	}
	if err := AssertIntegrationMultiMoneyAmountCustomerRequired(obj.AmountCustomer); err != nil {
		return err
	}
	return nil
}

// AssertRecurseIntegrationLineItemTotalTaxesRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of IntegrationLineItemTotalTaxes (e.g. [][]IntegrationLineItemTotalTaxes), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseIntegrationLineItemTotalTaxesRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aIntegrationLineItemTotalTaxes, ok := obj.(IntegrationLineItemTotalTaxes)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertIntegrationLineItemTotalTaxesRequired(aIntegrationLineItemTotalTaxes)
	})
}
