/*
 * Integration stubs
 *
 * Stubs for implementing a REVER integration
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

// LineItemTotal - total amount of the line including discounts and taxes total = (subtotal - total_discounts) + total_taxes this is going to be the amount to be refunded (multiplied by items_returned/quantity)
type LineItemTotal struct {

	AmountShop MultiMoneyAmountShop `json:"amount_shop"`

	AmountCustomer MultiMoneyAmountCustomer `json:"amount_customer"`
}

// AssertLineItemTotalRequired checks if the required fields are not zero-ed
func AssertLineItemTotalRequired(obj LineItemTotal) error {
	elements := map[string]interface{}{
		"amount_shop": obj.AmountShop,
		"amount_customer": obj.AmountCustomer,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertMultiMoneyAmountShopRequired(obj.AmountShop); err != nil {
		return err
	}
	if err := AssertMultiMoneyAmountCustomerRequired(obj.AmountCustomer); err != nil {
		return err
	}
	return nil
}

// AssertRecurseLineItemTotalRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of LineItemTotal (e.g. [][]LineItemTotal), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseLineItemTotalRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aLineItemTotal, ok := obj.(LineItemTotal)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertLineItemTotalRequired(aLineItemTotal)
	})
}
