/*
 * Integration stubs
 *
 * Stubs for implementing a REVER integration
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

// LineItemSubtotal - sub total amount of the line before discounts and taxes `subtotal = unit_price * quantity`
type LineItemSubtotal struct {

	AmountShop MultiMoneyAmountShop `json:"amount_shop"`

	AmountCustomer MultiMoneyAmountCustomer `json:"amount_customer"`
}

// AssertLineItemSubtotalRequired checks if the required fields are not zero-ed
func AssertLineItemSubtotalRequired(obj LineItemSubtotal) error {
	elements := map[string]interface{}{
		"amount_shop": obj.AmountShop,
		"amount_customer": obj.AmountCustomer,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertMultiMoneyAmountShopRequired(obj.AmountShop); err != nil {
		return err
	}
	if err := AssertMultiMoneyAmountCustomerRequired(obj.AmountCustomer); err != nil {
		return err
	}
	return nil
}

// AssertRecurseLineItemSubtotalRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of LineItemSubtotal (e.g. [][]LineItemSubtotal), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseLineItemSubtotalRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aLineItemSubtotal, ok := obj.(LineItemSubtotal)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertLineItemSubtotalRequired(aLineItemSubtotal)
	})
}
