/*
 * Integration stubs
 *
 * Stubs for implementing a REVER integration
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

// IntegrationMultiMoney - An amount that is expressed in two currencies: the shop and the customer one. They can be the same or not. 
type IntegrationMultiMoney struct {

	AmountShop IntegrationMultiMoneyAmountShop `json:"amount_shop"`

	AmountCustomer IntegrationMultiMoneyAmountCustomer `json:"amount_customer"`
}

// AssertIntegrationMultiMoneyRequired checks if the required fields are not zero-ed
func AssertIntegrationMultiMoneyRequired(obj IntegrationMultiMoney) error {
	elements := map[string]interface{}{
		"amount_shop": obj.AmountShop,
		"amount_customer": obj.AmountCustomer,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertIntegrationMultiMoneyAmountShopRequired(obj.AmountShop); err != nil {
		return err
	}
	if err := AssertIntegrationMultiMoneyAmountCustomerRequired(obj.AmountCustomer); err != nil {
		return err
	}
	return nil
}

// AssertRecurseIntegrationMultiMoneyRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of IntegrationMultiMoney (e.g. [][]IntegrationMultiMoney), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseIntegrationMultiMoneyRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aIntegrationMultiMoney, ok := obj.(IntegrationMultiMoney)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertIntegrationMultiMoneyRequired(aIntegrationMultiMoney)
	})
}
