/*
 * Integration stubs
 *
 * Stubs for implementing a REVER integration
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

// IntegrationShippingAmount - Total amount charged as shipping costs. 
type IntegrationShippingAmount struct {

	AmountShop IntegrationMultiMoneyAmountShop `json:"amount_shop"`

	AmountCustomer IntegrationMultiMoneyAmountCustomer `json:"amount_customer"`
}

// AssertIntegrationShippingAmountRequired checks if the required fields are not zero-ed
func AssertIntegrationShippingAmountRequired(obj IntegrationShippingAmount) error {
	elements := map[string]interface{}{
		"amount_shop": obj.AmountShop,
		"amount_customer": obj.AmountCustomer,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertIntegrationMultiMoneyAmountShopRequired(obj.AmountShop); err != nil {
		return err
	}
	if err := AssertIntegrationMultiMoneyAmountCustomerRequired(obj.AmountCustomer); err != nil {
		return err
	}
	return nil
}

// AssertRecurseIntegrationShippingAmountRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of IntegrationShippingAmount (e.g. [][]IntegrationShippingAmount), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseIntegrationShippingAmountRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aIntegrationShippingAmount, ok := obj.(IntegrationShippingAmount)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertIntegrationShippingAmountRequired(aIntegrationShippingAmount)
	})
}
