/*
 * Integration stubs
 *
 * Stubs for implementing a REVER integration
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

// IntegrationMultiMoneyAmountShop - Amount in the shop currency. Useful for accounting purposes. 
type IntegrationMultiMoneyAmountShop struct {

	// amount (optionally with decimals), without currency symbol and thousands separator
	Amount float32 `json:"amount"`

	// three-letter code as ISO 4217 currency code.  Examples: EUR, USD, JPY, GBP... The currency must be supported by REVER. 
	Currency string `json:"currency"`
}

// AssertIntegrationMultiMoneyAmountShopRequired checks if the required fields are not zero-ed
func AssertIntegrationMultiMoneyAmountShopRequired(obj IntegrationMultiMoneyAmountShop) error {
	elements := map[string]interface{}{
		"amount": obj.Amount,
		"currency": obj.Currency,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseIntegrationMultiMoneyAmountShopRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of IntegrationMultiMoneyAmountShop (e.g. [][]IntegrationMultiMoneyAmountShop), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseIntegrationMultiMoneyAmountShopRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aIntegrationMultiMoneyAmountShop, ok := obj.(IntegrationMultiMoneyAmountShop)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertIntegrationMultiMoneyAmountShopRequired(aIntegrationMultiMoneyAmountShop)
	})
}
