/*
 * Integration stubs
 *
 * Stubs for implementing a REVER integration
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

// IntegrationReturnRequest - Payload for the method CreateOrUpdateReturn.
type IntegrationReturnRequest struct {

	// List of items to mark (or unmark) as returned. Can't be empty.
	Returns []IntegrationReturnRequestItem `json:"returns"`
}

// AssertIntegrationReturnRequestRequired checks if the required fields are not zero-ed
func AssertIntegrationReturnRequestRequired(obj IntegrationReturnRequest) error {
	elements := map[string]interface{}{
		"returns": obj.Returns,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Returns {
		if err := AssertIntegrationReturnRequestItemRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseIntegrationReturnRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of IntegrationReturnRequest (e.g. [][]IntegrationReturnRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseIntegrationReturnRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aIntegrationReturnRequest, ok := obj.(IntegrationReturnRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertIntegrationReturnRequestRequired(aIntegrationReturnRequest)
	})
}
