/*
 * Integration stubs
 *
 * Stubs for implementing a REVER integration
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

type Option struct {

	// Name of the option
	Name string `json:"name"`

	// Value of the option
	Value string `json:"value"`
}

// AssertOptionRequired checks if the required fields are not zero-ed
func AssertOptionRequired(obj Option) error {
	elements := map[string]interface{}{
		"name": obj.Name,
		"value": obj.Value,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseOptionRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Option (e.g. [][]Option), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseOptionRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aOption, ok := obj.(Option)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertOptionRequired(aOption)
	})
}
