/*
 * Integration stubs
 *
 * Stubs for implementing a REVER integration
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	server "github.com/itsrever/integration/server/go"
)

func main() {
	log.Printf("Server started")

	IntegrationApiService := server.NewIntegrationApiService()
	IntegrationApiController := server.NewIntegrationApiController(IntegrationApiService)

	router := server.NewRouter(IntegrationApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
