/*
 * Integration stubs
 *
 * Stubs for implementing a REVER integration
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"flag"
	"fmt"
	"log"
	"net/http"

	server "github.com/itsrever/integration/server/go"
	"github.com/itsrever/integration/server/refund"
)

const defaultPort = 8080

func main() {
	log.Printf("Reading config...")
	authFlagPtr := flag.String("auth", "api-key", "Authentication method (api-key | oauth2)")
	portFlagPtr := flag.Int("port", defaultPort,
		fmt.Sprintf("The TCP port to listen on. Default is %v", defaultPort))

	flag.Parse()
	log.Printf("Server starting...")

	refundManager := refund.New()
	IntegrationApiService := server.NewIntegrationApiService(refundManager)
	IntegrationApiController := server.NewIntegrationApiController(IntegrationApiService)

	router := server.NewRouter(IntegrationApiController)

	log.Printf("Using auth: %v...", *authFlagPtr)
	if *authFlagPtr == "oauth2" {
		log.Printf("OAuth2 not implemented yet...")
		return
	} else {
		router.Use(apiKeyAuthMiddleware)
	}

	log.Printf("Start listening on %v...", *portFlagPtr)

	//nolint:gosec
	log.Fatal(http.ListenAndServe(":8080", router))
}

func apiKeyAuthMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		apiKey := r.Header.Get("x-rever-api-key")
		//nolint:gosec
		if apiKey != "valid-api-key" {
			http.Error(w, "Unauthorized", http.StatusUnauthorized)
			return
		}
		next.ServeHTTP(w, r)
	})
}
